spring:
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/configs
  profiles:
     active: native

server:
  port: 80

security:
  user:
    password: ${CONFIG_SERVICE_PASSWORD}