version: '2.1'
services:

  database:
      image: postgres:9.5
      environment:
        - POSTGRES_PASSWORD
        - POSTGRES_USER
        - POSTGRES_DB
      ports:
        - 5432:5432

  config:
      build: config
      depends_on:
        database:
          condition: service_started

  auth-server:
      build: auth-server
      environment:
        - AUTH_KEYSTORE_PASSWORD
        - AUTH_KEYSTORE_ALIAS_PASSWORD
        - AUTH_KEYSTORE_ALIAS
        - CLIENT_ID
        - CLIENT_PASSWORD
      ports:
        - 8082:80
      depends_on:
        config:
          condition: service_healthy

  gateway:
      build: api-gateway
      ports:
        - 8080:80
      depends_on:
        config:
          condition: service_healthy
        registry:
          condition: service_healthy

  registry:
      build: registry
      ports:
        - 8081:80
      depends_on:
        config:
          condition: service_healthy

  product-service:
      build: product-service
      depends_on:
        config:
          condition: service_healthy
        registry:
          condition: service_healthy
      environment:
        - POSTGRES_PASSWORD
        - POSTGRES_USER
        - POSTGRES_DB