version: '2.1'
services:
  config:
      build: config
      ports:
        - 8888:8888
  gateway:
      build: api-gateway
  registry:
      build: registry
  sandbox:
      build: sandbox
      ports:
        - 7000:7000