version: '2.1'
services:
  config:
      build: config
      environment:
        - DATABASE_USER_NAME
        - DATABASE_USER_PASSWORD

  gateway:
      build: api-gateway
      ports:
        - 8080:80
      depends_on:
        config:
          condition: service_healthy
        registry:
          condition: service_healthy

  registry:
      build: registry
      ports:
        - 8081:80
      depends_on:
        config:
          condition: service_healthy

  product-service:
      build: product-service
      depends_on:
        config:
          condition: service_healthy
        registry:
          condition: service_healthy