version: '2.1'
services:
  config:
      build: config
      ports:
        - 8888:8888
      environment:
        - DATABASE_USER_NAME
        - DATABASE_USER_PASSWORD
  gateway:
      build: api-gateway
      ports:
        - 4000:4000
  registry:
      build: registry
      ports:
        - 8761:8761

  sandbox-service:
      build: sandbox
      ports:
        - 7000:7000
  product-service:
      build: product-service
      ports:
        - 7001:7001