spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/shop
    username: ${DATABASE_USER_NAME}
    password: ${DATABASE_USER_PASSWORD}
    platform: POSTGRESQL
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true


server:
  context-path: /products
  port: 7001