

server:
  contextPath: /uaa
  port: 5000

credentials:
  keystore-password: ${AUTH_KEYSTORE_PASSWORD}
  keystore-alias: ${AUTH_KEYSTORE_ALIAS}
  keystore-alias-password: ${AUTH_KEYSTORE_PASSWORD}
  client-password: ${CLIENT_PASSWORD}
  client-id: ${CLIENT_ID}